channels:
  4HePotA [K]:
    backend: readout
    temperature:
      device: Lakeshore350
      channel: A
    webserver:
      controller: False
      display: True

  4pumpA [K]:
    backend: software_pid
    temperature:
      device: Lakeshore218
      channel: 2
    actuator:
      device: MX103QP
      channel: 1
    pid:
      kp: 0.22
      ki: 0.0008
      kd: 0.5
      min: 0.0 
      max: 30.0
    webserver:
      controller: True
      units: K
      display: True

  4switchA [K]:
    backend: manual
    temperature:
      device: Lakeshore218
      channel: 3
    actuator:
      device: GPDX303SA
      channel: 1
    webserver:
      controller: True
      units: V
      display: True

  4pumpAheat [V]:
    backend: readout_V
    voltage:
      device: MX103QP
      channel: 1

  4switchAheat [V]:
    backend: readout_V
    voltage:
      device: GPDX303SA
      channel: 1

  3HePotA [K]:
    backend: readout
    temperature:
      device: Lakeshore350
      channel: B
    webserver:
      controller: False
      display: True

  3pumpA [K]:
    backend: software_pid
    temperature:
      device: Lakeshore218
      channel: 5
    actuator:
      device: MX103QP
      channel: 2
    pid:
      kp: 0.22
      ki: 0.0008
      kd: 0.5
      min: 0.0 
      max: 30.0
    webserver:
      controller: True
      units: K
      display: True

  3switchA [K]:
    backend: manual
    temperature:
      device: Lakeshore218
      channel: 6
    actuator:
      device: GPDX303SA
      channel: 2
    webserver:
      controller: True
      units: V
      display: True

  3pumpAheat [V]:
    backend: readout_V
    voltage:
      device: MX103QP
      channel: 2

  3switchAheat [V]:
    backend: readout_V
    voltage:
      device: GPDX303SA
      channel: 2

  4HePotB [K]:
    backend: readout
    temperature:
      device: Lakeshore350
      channel: C
    webserver:
      controller: False
      display: True

  4pumpB [K]:
    backend: software_pid
    temperature:
      device: Lakeshore218
      channel: 1
    actuator:
      device: MX103QP
      channel: 4
    pid:
      kp: 0.22
      ki: 0.0008
      kd: 0.5
      min: 0.0 
      max: 30.0
    webserver:
      controller: True
      units: K
      display: True

  4switchB [K]:
    backend: manual
    temperature:
      device: Lakeshore218
      channel: 7
    actuator:
      device: GPDX303SB
      channel: 1
    webserver:
      controller: True
      units: V
      display: True
  
  4pumpBheat [V]:
    backend: readout_V
    voltage:
      device: MX103QP
      channel: 4

  4switchBheat [V]:
    backend: readout_V
    voltage:
      device: GPDX303SB
      channel: 1

  3HePotB [K]:
    backend: readout
    temperature:
      device: Lakeshore350
      channel: D1
    webserver:
      controller: False
      display: True

  3pumpB [K]:
    backend: software_pid
    temperature:
      device: Lakeshore218
      channel: 4
    actuator:
      device: MX103QP
      channel: 3
    pid:
      kp: 0.22
      ki: 0.0008
      kd: 0.5
      min: 0.0 
      max: 30.0
    webserver:
      controller: True
      units: K
      display: True

  3switchB [K]:
    backend: manual
    temperature:
      device: Lakeshore218
      channel: 8
    actuator:
      device: GPDX303SB
      channel: 2
    webserver:
      controller: True
      units: V 
      display: True

  3pumpBheat [V]:
    backend: readout_V
    voltage:
      device: MX103QP
      channel: 3

  3switchBheat [V]:
    backend: readout_V
    voltage:
      device: GPDX303SB
      channel: 2

 #MC [K]:
 #   backend: readout
 #   temperature:
 #     device: Lakeshore350
 #     channel: D4

 # Still [K]:
 #   backend: readout
 #   temperature:
 #     device: Lakeshore350
 #     channel: D5

  Condenser [K]:
    backend: readout
    temperature:
      device: Lakeshore372
      channel: A
    webserver:
      controller: False
      display: True

  50K [K]:
    backend: readout
    temperature:
      device: Lakeshore336
      channel: D
    webserver:
      controller: False
      display: True

  4K [K]:
    backend: readout
    temperature:
      device: Lakeshore336
      channel: C
    webserver:
      controller: False
      display: True

  4HePotA [R]:
    backend: readout_R
    resistance:
      device: Lakeshore350
      channel: A

  4pumpA [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 2

  4switchA [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 3
    
  3HePotA [R]:
    backend: readout_R
    resistance:
      device: Lakeshore350
      channel: B

  3pumpA [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 5

  3switchA [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 6

  4HePotB [R]:
    backend: readout_R
    resistance:
      device: Lakeshore350
      channel: C

  4pumpB [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 1

  4switchB [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 7
  
  3HePotB [R]:
    backend: readout_R
    resistance:
      device: Lakeshore350
      channel: D1

  3pumpB [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 4
      
  3switchB [V]:
    backend: readout_V
    voltage:
      device: Lakeshore218
      channel: 8

 #MC [R]:
 #   backend: readout_R
 #   temperature:
 #     device: Lakeshore350
 #     channel: D4

 # Still [R]:
 #   backend: readout_R
 #   temperature:
 #     device: Lakeshore372
 #     channel: A

  Condenser [R]:
    backend: readout_R
    resistance:
      device: Lakeshore372
      channel: A

  50K [V]:
    backend: readout_V
    voltage:
      device: Lakeshore336
      channel: D

  4K [V]:
    backend: readout_V
    voltage:
      device: Lakeshore336
      channel: C






#
#  3PumpA:
#   backend: software_pid
#   temperature:
#     device: ls350
#     channel: A
#   actuator:
#      device: psu_pumps
#      channel: 1
#    pid:
#      kp: 5.0
#      ki: 0.3
#      kd: 0.0
#
#  4PumpB:
#    backend: software_pid
#    temperature:
#      device: ls350
#      channel: A
#    actuator:
#      device: psu_pumps
#      channel: 1
#    pid:
#      kp: 5.0
#      ki: 0.3
#      kd: 0.0
#
#  3PumpB:
#    backend: software_pid
#    temperature:
#      device: ls350
#      channel: A
#    actuator:
#      device: psu_pumps
#      channel: 1
#    pid:
#      kp: 5.0
#      ki: 0.3
#      kd: 0.0
#
#  Still:
#    backend: manual
#    temperature:
#      device: ls350
#      channel: C
#    actuator:
#      device: ls350
#      channel: heater
