# Config for database reading, First type into terminal: ssh -f -nNT -L 8086:localhost:8082 mu2edaq2 (Ports will be different for you, check first)
options = [
    "localhost",     # host
    "axion_reader",  # user
    8086,            # port of the db
    "axion_db"       # database
]
START_TIME = "2025-05-01 12:00:00" # Start time for data reading
END_TIME   = "2025-05-01 18:00:00" # End time for data reading
channels = ["4K [K]", " CalibrationPSU [V]"]  # List of channels to read
log_plot = False  # bool, whether to log scale the plot or not
